# Generated by Django 5.1.1 on 2024-09-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=20, max_digits=40)),
                ('amount0', models.DecimalField(decimal_places=20, max_digits=40)),
                ('amount1', models.DecimalField(decimal_places=20, max_digits=40)),
                ('owner', models.CharField(max_length=255)),
                ('pool_id', models.CharField(max_length=255)),
                ('tickLower', models.IntegerField()),
                ('tickUpper', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'burn',
            },
        ),
        migrations.CreateModel(
            name='Mint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=20, max_digits=40)),
                ('amount0', models.DecimalField(decimal_places=20, max_digits=40)),
                ('amount1', models.DecimalField(decimal_places=20, max_digits=40)),
                ('owner', models.CharField(max_length=255)),
                ('pool_id', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('tickLower', models.IntegerField()),
                ('tickUpper', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mint',
            },
        ),
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('timestamp', models.DateTimeField(db_index=True, primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=10, max_digits=30)),
                ('high', models.DecimalField(decimal_places=10, max_digits=30)),
                ('low', models.DecimalField(decimal_places=10, max_digits=30)),
                ('close', models.DecimalField(decimal_places=10, max_digits=30)),
                ('volume', models.DecimalField(decimal_places=20, max_digits=40)),
            ],
            options={
                'db_table': 'ohlcv',
            },
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('amount0', models.DecimalField(decimal_places=20, max_digits=40)),
                ('amount1', models.DecimalField(decimal_places=20, max_digits=40)),
                ('pool_id', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('sqrtPriceX96', models.DecimalField(decimal_places=40, max_digits=80)),
                ('tick', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'swap',
            },
        ),
    ]
