# Generated by Django 5.1.1 on 2024-09-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burn',
            name='event_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='burn',
            name='owner',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='burn',
            name='pool_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mint',
            name='event_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mint',
            name='owner',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mint',
            name='pool_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mint',
            name='sender',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='swap',
            name='event_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='swap',
            name='pool_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='swap',
            name='recipient',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='swap',
            name='sender',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='burn',
            unique_together={('event_id', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='mint',
            unique_together={('event_id', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='swap',
            unique_together={('event_id', 'timestamp')},
        ),
    ]
